### ISSUE TITLE
Encoding errors

### ISSUE THREAD

**Issue by enriquesanz** [SIMPATICOProject/aac#4]
When a new user is signed up, codification of tilded characters goes wrong, so when user data is retrieved it is bad rendered in the front end.

Example:

When receiving the confirmation email everything looks right.

![correo](https://user-images.githubusercontent.com/332383/31171406-dafe58fa-a8ff-11e7-9de4-038b5c78f8b9.PNG)

And the 'registration' table is ok:

![registration](https://user-images.githubusercontent.com/332383/31171470-18b0c0ca-a900-11e7-8479-e2d7b1a01459.png)

But when the process ends, the 'user' table encoding is wrong:

![user](https://user-images.githubusercontent.com/332383/31171501-34a8450a-a900-11e7-9fc6-7aad06932165.png)

**Comment by jrgaston-hib** [comment]
In new version https://github.com/SIMPATICOProject/aac/commit/d1c728d42be193c673970c9422b5124e37b0173d
Now it's working that expected
